### ISSUE TITLE
Wrong Number of Polygons in Multipolygon 

### ISSUE THREAD

**Issue by cajonKA** [twpayne/go-geom#112]
When I unmarshal the following GeoJson Multipolygon and later call NumPolygons on it, I would expect to get 2 as result, but the result is 1, because endss is <code>[[10 20]]</code> instead of <code>[[10] [20]]</code>
<code>{"type":"MultiPolygon","coordinates":[[[[0,35],[0,40],[10,40],[10,35],[0,35]],[[6,48],[6,51],[10,51],[10,48],[6,48]]]]}</code>

Is this a bug or am I missing some important point ?

**Comment by twpayne** [comment]
Here's the hierarchy:

* A point is `[]float64`.
* A ring is a sequence of points, i.e. `[][]float64`.
* A polygon is a sequence of rings, the first is the outer ring and any more are inner rings, i.e. `[][][]float64`. The outer ring is the boundary and inner rings are holes.
A multipolygon is a collection of polygons, i.e. `[][][][]float64`.

What you have in your GeoJSON is a multipolygon containing a single polygon with two rings:

```js
[
  [ // First polygon
    [[0,35],[0,40],[10,40],[10,35],[0,35]], // Outer ring
    [[6,48],[6,51],[10,51],[10,48],[6,48]]  // Inner ring
  ]
]
```

You probably want `coordinates` to be

```js
[
  [ // First poly
    [[0,35],[0,40],[10,40],[10,35],[0,35]] // Outer ring
  ],
  [ // Second poly
    [[6,48],[6,51],[10,51],[10,48],[6,48]] // Outer ring
  ]
]
```

**Comment by twpayne** [comment]
Please re-open this bug if needed.

**Comment by cajonKA** [comment]
So its a matter of clinching the numbers together ?
Then my question is, how can a inner and outer ring exist, if the two polys are far away from each other and don't intersect ?

**Comment by cajonKA** [comment]
I was not aware of this. Thanks for your help and for this really helpful lib.
