### ISSUE TITLE
new release? gopkg.in/DATA-DOG/go-sqlmock.v1 gone

### ISSUE THREAD

**Issue by quite** [twpayne/go-geom#130]
Could we have a new release? gopkg.in/DATA-DOG/go-sqlmock.v1 is gone. I see you've updated, but a release would be great for our go get -u :)

**Comment by twpayne** [comment]
Sure. I've just tagged `v1.0.5` for you.

I'll do some minor clean-ups (code formatting, stricter linting) and tag another release in the next few days, but there will be no functional changes.

**Comment by quite** [comment]
Excellent!
