### ISSUE TITLE
Incorrect Area of Polygon

### ISSUE THREAD

**Issue by anuragpant** [twpayne/go-geom#132]
I was trying to calculate the area of the following polygon:

{{{137.049165, -6.841482}, {134.911643, -7.375233}, {136.27792953096764, -14.715387}, {126.451361, -14.715387}, {126.451361, -8.775364}, {124.703997, -8.775364}, {122.7749, 0.57781}, {122.538722, 0.527397}, {122.53799, 0.53086}, {120.181633, 11.683563}, {132.868078, 12.94771}}} 

The area comes out to be 2348.29109861983 and the perimeter comes to 61.12660463619917. However, the actual area is around 322.43 and the actual perimeter is 81.35.

The weird thing is that shifting the points in a cyclic order (which maintains the order of the points of the polygon) results in different yet incorrect area and perimeter values. Any help with regards to this issue will be appreciated.

**Comment by aneeskA** [comment]
What was your issue? I am also having trouble using `Polygon.Area()` function. Just now logged issue: https://github.com/twpayne/go-geom/issues/139 . Can you please take a look?
