### ISSUE TITLE
encoding/geojson should support null geometry for Feature

### ISSUE THREAD

**Issue by vagruchi** [twpayne/go-geom#140]
Based on [spec](https://tools.ietf.org/html/rfc7946#section-3.2) geometry value in Feature can be  JSON null. But current implementation panics.

I can make pull request but I'm not sure where implement it. In Geometry.Decode or in Feature.UnmarshalJson. Changes in Geometry.Decode can affect GeometryCollection I think. 
Don't think it is right behavior. 
But library should not panic is incorrect GeoJSON provided IMO.

**Comment by twpayne** [comment]
Thanks very much for reporting this. I'd missed `null` geometries in features in the GeoJSON spec.

I think there are some subtle issues here. #141 adds naive support for `null` geometries, but I'm not sure if it's correct or not.

For sure, `go-geom` should not panic. This is definitely a bug.

**Comment by twpayne** [comment]
Fixed with #141.

**Comment by lelvisl** [comment]
Can you please tag a new release?

**Comment by twpayne** [comment]
Tagged `v1.0.6`.
