### ISSUE TITLE
encoding/wkt: wkt decoding case and space insensitive

### ISSUE THREAD

**Issue by otan** [twpayne/go-geom#151]
Trying to replace my WKT decoding from cgo-ing with GEOS with the go-geom one here.

Unfortunately, it doesn't work for a couple of cases, e.g.
* `POINT(1.0 1.0)` should work (no space between `POINT` and `(`)
* `point (1.0 1.0)` should work (case insensitive POINT)
* `POINTZ (1.0 1.0)` should work (`Z` dimension / layout does not need a space afterwards)

Wondering if it's worth using a grammar file (https://godoc.org/golang.org/x/tools/cmd/goyacc) to do this instead.

I can work on this at a later date, but flagging as an issue for now. (It's not straightforward based on the way things are tokenised right now in the wkt decoder)

**Comment by twpayne** [comment]
Thanks for flagging this. I agree that using a parser generator will give a more robust parser than the existing code. Feel free to rework the WKT parser completely if you want.
