### ISSUE TITLE
Reprojecting coordinates 

### ISSUE THREAD

**Issue by icholy** [twpayne/go-geom#179]
I'm writing some code to reproject geometries. Is it safe to modify the flat coordinates like this?

``` go
func TransformCoords(g geom.T, transform func(geom.Coord) geom.Coord) {
	flatCoords := g.FlatCoords()
	stride := g.Stride()
	for i := 0; i < len(flatCoords); i += stride {
		coord := transform(flatCoords[i : i+stride])
		copy(flatCoords[i:], coord)
	}
}
```

**Comment by twpayne** [comment]
Yes, it is safe to do this providing that the coordinates are not shared with any other geometry. This will of course modify the geometry in place. Coordinates are shared between geometries if you request a sub-geometry. For example, if you have a MultiLineString and call LineString(0) to get its first LineString, the returned LineString and the original MultiLineString will share coordinates. You can call Clone() to get a copy of a geometry with its own coordinates.

**Comment by icholy** [comment]
Would you consider adding a function like this to the `transforms` package?

**Comment by icholy** [comment]
My first iteration returned a new geometry with a copy of the coordinates, but that requires a type switch, a type assertion on the return value, and the cost of copying.

**Comment by twpayne** [comment]
#181 is a possible first implementation of this. I don't think any type assertions are needed. What are your thoughts?

**Comment by icholy** [comment]
@twpayne looks great!
