### ISSUE TITLE
WKT decoder could use re2c

### ISSUE THREAD

**Issue by twpayne** [twpayne/go-geom#180]
[re2c](http://re2c.org/) just got a Go backend, and looks like a nice little lexer for WKT. Maybe we could use this to provide more robust WKT decoding?

**Comment by otan** [comment]
CockroachDB uses YACC for SQL, I was thinking using that, but either works.
Thinking of doing this soon as it's on our roadmap.

**Comment by otan** [comment]
(but it may just be easier to write something without the parser for speed, heh)

**Comment by twpayne** [comment]
I would be happy with goyacc, re2c, or any other established parser generator. The main interest for me (at least) is first correctness and second performance. I think it is unlikely that the parser performance will be limiting given the relative simplicity of the WKT grammar, but of course we should test this assumption with profiling and benchmarks.

**Comment by otan** [comment]
heads up @andyyang890 is working on this for cockroach, we'll port it over once we have all our tests working against it
