### ISSUE TITLE
Unmarshal geoJSON []byte to MultiPoint

### ISSUE THREAD

**Issue by mbn18** [twpayne/go-geom#212]
This fail at compile
```
	data := geom.NewMultiPoint(geom.XYZM)
	err := geojson.Unmarshal(readFile(), data)
```
With error:
> cannot use data (variable of type *geom.MultiPoint) as type *geom.T in argument to geojson.Unmarshal:
> *geom.MultiPoint does not implement *geom.T (type *geom.T is pointer to interface, not interface)

The only way I could do it was using type hint:
```
func readMultiPoint() *geom.MultiPoint {
	var g geom.T
	err := geojson.Unmarshal(readFile(), &g)
	if err != nil {
		panic(err)
	}
	return g.(*geom.MultiPoint)
}
```

Is there a way to make the `geojson.Unmarshal` to work with `MultiPoint`? (or other geom).

**Comment by mbn18** [comment]
@twpayne , how should I check the result?

**Comment by twpayne** [comment]
You can use a type assertion in its two-valued form.
