### ISSUE TITLE
KML Decoding support

### ISSUE THREAD

**Issue by dbboyd17** [twpayne/go-geom#223]
Is there any plan to support decoding of KML data, such that the package could be used to translate from KML to GeoJSON?

**Comment by twpayne** [comment]
No. KML is a markup language, not a data representation language. Beyond simple geometries, there is no canonical way to convert KML to GeoJSON.

You may find the types in [github.com/twpayne/go-kml](https://github.com/twpayne/go-kml) useful in your own converter.

**Comment by dbboyd17** [comment]
Tom.

I take your point, and thanks for the exceedingly quick response!

I did find https://github.com/amundsentech/kml-decode

I’ll do a bit more digging/experimentation.

 

Cheers, Bruce.
