### ISSUE TITLE
Support for GPS point calculation?

### ISSUE THREAD

**Issue by luoyh22** [twpayne/go-geom#227]
As there is SRID item for geom objector, I think the functions such as Length, Intersect etc. should support the (longitude, latitude) format geoms.
What I expect is calculate the distance between two points in planer as (longitude, latitude) format, in Plane not Spherical.  Do you have the plan for this feature?

**Comment by twpayne** [comment]
No. This is specifically out-of-scope for go-geom.

go-geom specifically a low-level library for representing geometries. It maintains the SRID of geometries for ease of integration with GIS systems.

The distance, area, etc. calculations depend on the projection used and the application's need. In many cases, the calculations are extremely complex. For this, I recommend using [PROJ](https://proj.org/). I have written Go bindings for PROJ at [github.com/twpayne/go-proj](https://github.com/twpayne/go-proj).
