### ISSUE TITLE
get v1.5.2 and get some trouble

### ISSUE THREAD

**Issue by jhaoheng** [twpayne/go-geom#233]
<img width="861" alt="截圖 2023-08-08 下午12 07 07" src="https://github.com/twpayne/go-geom/assets/1822475/84efc4fb-b7c5-4e5a-9790-0a54fbd8e557">

hi there

As the picture.
I got the trouble when I use `go get github.com/twpayne/go-geom`

thank you

**Comment by twpayne** [comment]
This looks like a problem with your Go modules setup or proxy. This is not related to go-geom.
