### ISSUE TITLE
geom.Bounds implementing geom.T

### ISSUE THREAD

**Issue by thomascoquet** [twpayne/go-geom#234]
Hi,

First of all, thanks for the library. 

I was using the `geom.Bounds` object recently and was thinking that it would be a nice addition if it implemented the `geom.T` interface.

For example, one could set a SRID for a `Bounds` object (why shouldn't it have one? ;-) ).
Could behave as a polygon with four vertices for `FlatCoords()`, `Ends()`, `Endss()`.

Happy to submit a PR if you're interested.
Thomas

**Comment by twpayne** [comment]
This is unlikely to be possible as `Bounds` uses a different underlying representation to a `geom.T` and its coordinates are not stored directly.

If you want to convert a `Bounds` to a `geom.T` you can use the existing [`Bounds.Polygon` method](https://pkg.go.dev/github.com/twpayne/go-geom#Bounds.Polygon).
