### ISSUE TITLE
cgo panic

### ISSUE THREAD

**Issue by ruierzhao** [twpayne/go-geom#241]
windows10 ,amd64, mingw :
when I run ```go run main.go```,it occur this ```cannot use (_Ctype_ulong)(len(wkb)) (value of type _Ctype_ulong) as _Ctype_ulonglong value in variable declaration``` ,I'm confused ，what is matter

**Comment by twpayne** [comment]
go-geom does not use cgo. Whatever your problem is, it has nothing to do with go-geom.

**Comment by ruierzhao** [comment]
Im so sorry,it panic when I use ```go-geos```,but I write an issuse on this reop.In order to solve my problem as soon as possible, I have given up using golang. anyway, thank you.
