### ISSUE TITLE
MultiLineStringZ & sqlc interaction

### ISSUE THREAD

**Issue by bastiankoetsier** [twpayne/go-geom#256]
Hey there, 
first of all thank you for your amazing library! 

I do have a question regarding a very specific scenario: 
My Column in my postgres/postgis db is a `geometry(MultiLineStringZ, 25833)` and I trying to use sqlc to generate my db code by [overriding](https://docs.sqlc.dev/en/latest/howto/overrides.html) the specific type for this column with your MultiLineString typew provided by this package. Unfortunately, sqlc does not seem to understand this 😞  For my limited understanding of postgis so far, this _should_ be working but I might be totally off here 😅 Any hints are appreciated!

Greetings from Berlin!

**Comment by twpayne** [comment]
Can you provide a minimal example (with code) that demonstrates the problem?

**Comment by bastiankoetsier** [comment]
(thanks for the swift reply!)
I tried to follow this https://docs.sqlc.dev/en/latest/reference/datatypes.html#using-github-com-twpayne-go-geom 
![SCR-20240904-lmsw](https://github.com/user-attachments/assets/1c1e915f-ca34-49e7-ba57-ede95d5ed012)

The schema is super big but this is basically the column definition: `geometry(MultiLineStringZ, 25833)` 
 When I try to run the query I get 
 ```
 can't scan into dest[22]: cannot scan NULL into *geom.MultiPolygon
 ```
 
 Let me know if you need any other info!

**Comment by bastiankoetsier** [comment]
okay, I trimmed it down to only one column that gets returned. Now I am getting: 
` can't scan into dest[0]: cannot scan unknown type (OID 83165) in text format into *geom.MultiPolygon
`

**Comment by twpayne** [comment]
You are calling [`github.com/twpayne/pgx-geom.Register`](https://pkg.go.dev/github.com/twpayne/pgx-geom#Register), right?

**Comment by bastiankoetsier** [comment]
yeah of course not .... 🙈  After I figured out I need only single Polygons instead of the multi-variant, it was working as expected. Thank you very much for your help, highly appreciated!
