### ISSUE TITLE
Support for WKT

### ISSUE THREAD

**Issue by kostub** [twpayne/go-geom#47]
Hi,
Are you going to add support for encoding/decoding WKT as well?

Thanks,
Kostub

**Comment by twpayne** [comment]
Yes, this is planned.

There is support for WKT encoding in this branch: https://github.com/twpayne/go-geom/compare/improvement/wkt (not yet merged).

I'm still looking at options for writing in WKT decoder and am not yet sure whether to hand-write a parser or using an existing tool like https://github.com/pointlander/peg or [yacc](https://golang.org/cmd/yacc/).

**Comment by kostub** [comment]
Thanks. I am interested in the decoding. (not so much in encoding). You have a parser in `gogeom`, but that repository says it is deprecated. Can that code be ported over?

Do you have rough idea when you think WKT will be available?

**Comment by twpayne** [comment]
I think https://github.com/twpayne/gogeom/tree/master/geom/encoding/wkt only contains an encoder, I don't think there's a decoder.

I don't personally have an immediate use case for WKT decoding (I use WKB instead) and as I'm developing go-geom in my spare time I can't promise when I will have time to do it.

That said, if performance is not an issue, then it should be possible to write a crude WKT decoder fairly quickly.

What are your requirements?

**Comment by twpayne** [comment]
Closed with #143.
