### ISSUE TITLE
LGPL license

### ISSUE THREAD

**Issue by manishrjain** [twpayne/go-geom#61]
go-geom has a file robust_determinate.go
https://github.com/twpayne/go-geom/blob/master/xy/internal/robustdeterminate/robust_determinate.go

Which is under LGPL. This makes it harder for us to import in our project which is under Apache 2.0 license, or use it for commercial purposes. Can this LGPL dependency be replaced, to make the library commercial usage compatible?

**Comment by twpayne** [comment]
Thanks for the diligence!

@ignatz points out that some versions of the LGPL are compatible with go-geom's 2-part BSD license. However, the licensing of this particular code is unclear: no LGPL version is specified.

Consequently, I've merged #62 which removes the LGPL code and everything that depends on it, pending replacement.

If you could contribute a replacement (the easiest way to do this is likely to find some BSD-compatible code and translate it to Go), that would be awesome! The only function that needs replacing is `xy/internal/robustdeterminate/robust_determinate.go`. You can then revert commit 2a0c7d6 to restore the functionality.

**Comment by twpayne** [comment]
I've opened #63 to track restoring the functionality.

**Comment by manishrjain** [comment]
Thanks a lot for quickly responding to this, @twpayne! Really appreciate it. I'll double check if this fixes the licensing issues.

**Comment by manishrjain** [comment]
Alright. I can confirm that it's fixed. I no longer see LGPL (btw, using fossa.io). Thanks again, @twpayne!
