### ISSUE TITLE
Restore convex hull functionality

### ISSUE THREAD

**Issue by twpayne** [twpayne/go-geom#63]
Convex hull functionality was removed in #62 in response to #61.

From https://github.com/twpayne/go-geom/issues/61#issuecomment-287302446:

> If you could contribute a replacement (the easiest way to do this is likely to find some BSD-compatible code and translate it to Go), that would be awesome! The only function that needs replacing is xy/internal/robustdeterminate/robust_determinate.go. You can then revert commit 2a0c7d6 to restore the functionality.

**Comment by jesseeichar** [comment]
Just a question regarding LGPL.  The Java code was LGPL but was ported to Go-geom by me so the actual code was done by me.  The robust determinate algorithm is pretty well-known.

https://www.cs.cmu.edu/~quake/robust.html

So is this code still LGPL?  I did copy the comments I admit.  What would it take to make this code considered to be "mine" (and thus go-geom compatible)

**Comment by manishrjain** [comment]
Based on some Google search -- "Translations (both to a different natural language and to a different programming language) are considered to be Derived Works."

So, derived works would still be subject to LGPL. For it to be different, it would have to be significantly different in structure.

**Comment by twpayne** [comment]
An implementation of the algorithm from the original paper referenced by @jesseeichar should also be sufficient. I had a quick look at the public domain C code on that page and it does not look to be particularly easy to translate to Go. An implementation from the paper would likely be easier.

**Comment by jackielii** [comment]
Are we able to re-write from this? https://github.com/golang/geo/blob/master/s2/predicates.go#L136

**Comment by jackielii** [comment]
I'm confused by the LGPL license statement. From JTS it states it's under EPL:
https://locationtech.github.io/jts/javadoc/org/locationtech/jts/algorithm/RobustDeterminant.html

**Comment by twpayne** [comment]
Fixed by #119.
