### ISSUE TITLE
Error when trying to Scan an EWKB polygon

### ISSUE THREAD

**Issue by zhiwei-nu** [twpayne/go-geom#82]
I am getting `sql: Scan error on column index 0: unsupported Scan, storing driver.Value type []uint8 into type *geom.Polygon` when trying to retrieve a geometry from my PostGIS database.

I'm doing a very simple `Scan` now like so:
```
rows, err := db.Query("SELECT geom FROM testgeoms")
for rows.Next() {
	var g gogeom.Polygon
	err := rows.Scan(&g)
}
```

Any pointers on what went wrong here?

**Comment by twpayne** [comment]
Hmmm, this is almost the exact case as tested in the [EWKB scan example](https://github.com/twpayne/go-geom/blob/master/encoding/ewkb/sql_test.go#L12).

I need more information to diagnose the problem, including:
* What database are you using?
* What is the type of the `geom` column in the `testgeoms` table?
* What is the exact value of `geom` in the row that is causing the error?

**Comment by zhiwei-nu** [comment]
@twpayne thanks for the reply!

> What database are you using?
Postgresql 9.6 with PostGIS extension

> What is the type of the `geom` column in the `testgeoms` table?
`geometry(Geometry ,4326)`, but I also tried with `geometry(Polygon, 4326)`

> What is the exact value of `geom` in the row that is causing the error?
`ST_PolygonFromText('POLYGON((5 3, 5 0, 7 0, 7 3, 5 3))'` though I think the coordinates don't really matter here. Also tried linestrings and points. FWIW if I use `ST_AsGeoJson` it returns a correct geojson. Maybe I can use the `geojson` package to work with that?

**Comment by twpayne** [comment]
Thanks, I'll try to duplicate this when I get home.

In the meantime, could you change your SQL query to call [ST_AsEWKB](http://www.postgis.net/docs/ST_AsEWKB.html) explicitly?

```sql
SELECT ST_AsEWKB(geom) FROM testgeoms;
```

I'd strongly recommend using EWKB rather than GeoJSON for interfacing with the database. EWKB is faster and doesn't risk losing precision (GeoJSON requires a `float64` -> `string` -> `float64` round trip).

**Comment by twpayne** [comment]
You might also need to add `binary_parameters=yes` to your datasource name when calling `sql.Open`, see #65.

**Comment by twpayne** [comment]
I duplicated the scenario in #83. It looks like `ST_AsEWKB` is needed, but `binary_parameters=yes` is not needed. Please can you try `ST_AsEWKB` and close this issue if this resolves your problem.

**Comment by twpayne** [comment]
As @vcabbage found in #65, `binary_parameters=yes` is needed if you're encoding EWKB values.

**Comment by zhiwei-nu** [comment]
@twpayne `ST_AsEWKB` / `binary_parameters=yes` doesn't work for me - getting the same error. Here's some more info:

`ST_AsGeoJSON`
![image](https://user-images.githubusercontent.com/27188482/28347868-45b0f6ba-6c6c-11e7-86aa-d5bec30f63ac.png)

`ST_AsEWKB`
![image](https://user-images.githubusercontent.com/27188482/28347888-5fbafc54-6c6c-11e7-8eba-8c17dd61d764.png)

**Comment by zhiwei-nu** [comment]
This is what i'm importing by the way, in case I did it wrong : `gogeom "github.com/twpayne/go-geom"`

**Comment by zhiwei-nu** [comment]
Figured I might as well put the whole cleaned up source code here:

```
package main

import (
	"database/sql"
	_ "github.com/lib/pq"
	gogeom "github.com/twpayne/go-geom"
	"log"
)

func check(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	db, err := sql.Open("postgres", "user=postgres dbname=gisdb sslmode=disable binary_parameters=yes")
	check(err)
	rows, err := db.Query("SELECT ST_GeomFromEWKB(geom) FROM testgeoms")
	check(err)
	defer rows.Close()
	for rows.Next() {
		var g gogeom.Polygon
		err := rows.Scan(&g)

		if err != nil {
			log.Fatal(err)
		}
		check(err)
		log.Printf("Geoms: %v\n", g)
	}
}
```

**Comment by twpayne** [comment]
Please follow [the example](https://github.com/twpayne/go-geom/blob/master/encoding/ewkb/postgis_test.go) carefully :)

* You need to import `github.com/twpayne/go-geom/encoding/ewkb`.
* Your polygon must be a `ewkb.Polygon`.
* Your query must use `ST_AsEWKB`.

**Comment by zhiwei-nu** [comment]
@twpayne Thank you! Using `ewkb.Polygon` and `ST_AsEWKB` works perfectly :+1:
