### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by nicola-spb** [twpayne/go-geom#89]
I want to use **go-geom** with postgis and postgres. But I didn`t find examples. 
Can I use it with postgis? 

Should I use ewkb (ST_AsEWKB) for your types of polygon and point or I should do something else?

Please add more examples.

**Comment by twpayne** [comment]
There are examples in the docs:

https://godoc.org/github.com/twpayne/go-geom/encoding/ewkb

There's a specific PostGIS test here:

https://github.com/twpayne/go-geom/blob/master/encoding/ewkb/postgis_test.go

Is this sufficient for you?

**Comment by nicola-spb** [comment]
Thank you. 
P.S. Sorry I searched examples but I forgot tests.
