### ISSUE TITLE
What about NullPointer, NullPolygon for sql?

### ISSUE THREAD

**Issue by nicola-spb** [twpayne/go-geom#90]
Do you have null types for geometry (NullPointer, NullPolygon etc) ?
https://github.com/twpayne/go-geom/blob/master/encoding/ewkb/sql.go

P.S. like NullString, NullTime ...

**Comment by twpayne** [comment]
Please test #91, which should add this functionality to all EWKB geometry types.

**Comment by nicola-spb** [comment]
It`s ok. Thank you.
